# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170523_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='classroom',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='classroom',
            field=models.ManyToManyField(to='blog.Classroom'),
        ),
    ]
