# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170523_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='classroom',
            new_name='classrooms',
        ),
    ]
